//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanDienThoatBTL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NoiXuatXu
    {
        public int MaXuatXu { get; set; }
        public string NoiXuatXu1 { get; set; }
    }
}
